/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Core")]
    [LuaRegisterType(0x367ffc9d1aef367e, typeof(LuaBehaviour))]
    public class Core : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ca114ced905944940b4ebe8b943db279";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_greenText = default;
        [SerializeField] public UnityEngine.GameObject m_bigGreenText = default;
        [SerializeField] public UnityEngine.GameObject m_bigRedText = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_greenText),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_bigGreenText),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_bigRedText),
            };
        }
    }
}

#endif
