/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FactoryScript")]
    [LuaRegisterType(0xd8746df0b2b87142, typeof(LuaBehaviour))]
    public class FactoryScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ca5b08074d4b2ac4fb4d71934263e063";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_spawnPoint = default;
        [SerializeField] public UnityEngine.GameObject m_donutMaker = default;
        [SerializeField] public UnityEngine.GameObject m_glazer = default;
        [SerializeField] public UnityEngine.GameObject m_icer = default;
        [SerializeField] public UnityEngine.GameObject m_endOfConveyor = default;
        [SerializeField] public UnityEngine.GameObject m_wallLabel = default;
        [SerializeField] public UnityEngine.GameObject m_plainDonutPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_chocolateDonutPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_cakeDonutPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_cinnamonDonutPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_appleDonutPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_spawnPoint),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_donutMaker),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_glazer),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_icer),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_endOfConveyor),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_wallLabel),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_plainDonutPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_chocolateDonutPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_cakeDonutPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_cinnamonDonutPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_appleDonutPrefab),
            };
        }
    }
}

#endif
