/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UpgradeButton")]
    [LuaRegisterType(0xc93760836cf287c7, typeof(LuaBehaviour))]
    public class UpgradeButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "34b83489f37f3154988b1940aa2fefb3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_isUpgrade = true;
        [SerializeField] public System.String m_upgradeName = "";
        [SerializeField] public System.String m_prereqName = "";
        [SerializeField] public System.Double m_prereqLevel = 0;
        [SerializeField] public UnityEngine.GameObject m_label = default;
        [SerializeField] public UnityEngine.GameObject m_factory = default;
        [SerializeField] public UnityEngine.GameObject m_lever = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_isUpgrade),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_upgradeName),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_prereqName),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_prereqLevel),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_label),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_factory),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_lever),
            };
        }
    }
}

#endif
